name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Hello 👋 Thank you for submitting an issue.
        Before you start, please make sure your issue is understandable and reproducible.

        Please ensure you have also read and understand the (contributing guide)[https://github.com/strapi/strapi/blob/main/CONTRIBUTING.md#reporting-an-issue].
  
  - type: markdown
    attributes:
      value: |
        ### Required System Information

  - type: input
    id: node-version
    attributes:
      label: Node Version
      description: What version of Node are you using?
      placeholder: v14.19.2 for example
    validations:
      required: true

  - type: input
    id: npm-version
    attributes:
      label: NPM Version
      description: What version of NPM are you using?
      placeholder: v6.11.1 for example
    validations:
      required: true

  - type: input
    id: strapi-version
    attributes:
      label: Strapi Version
      description: What version of Strapi are you using?
      placeholder: v4.3.6 for example
    validations:
      required: true

  - type: input
    id: db-version
    attributes:
      label: Database Version
      description: What database and version are you using?
      placeholder: Postgres v14.x.x for example
    validations:
      required: false 

  - type: input
    id: os-version
    attributes:
      label: Operating System Version
      description: What OS and version are you using?
      placeholder: MacOS 10.15.11 for example
    validations:
      required: true
  
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: How can we make this happen for us?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  
  - type: textarea
    attributes:
      label: Code Snippets
      description: |
        If applicable, add code samples to help explain your problem.

        Tip: You can paste your code here using markdown
    validations:
      required: false
  
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true